# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.smartenergy_goecharger: debug
    custom_components.hacs: debug
    aiogithubapi: debug

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

smartenergy_goecharger:
  chargers:
    - name: charger1
      host: http://mock-api:4000
      api_token: TEST
